// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzgfxdskyjpqkoqqcktp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6Z2Z4ZHNreWpwcWtvcXFja3RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTY5NTMsImV4cCI6MjA2NDAzMjk1M30.kYDvKdGt_LE9YqXTlyMmPHkyNwu5a-qyd_apAFc13jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);